version: '3.8'

services:
  todo-app: # задаем имя любое
    container_name: my_super_docker-todo-app
    restart: unless-stopped
    build: ./ #Ишет докер файл на основания которого соберет докер файл
    command: ./todo-app # Команды которые будут выполняться внутри контейнера в нашем случи запуск контейнера
    ports: #порты запуска
      - '${APP_PORT:-4000}:4000'
    depends_on: #указываем зависимые контейнеры, наше приложение не запуститься пока не запустяться перечисленные контейнеры
      - db
    environment: #передаем перменные окружения
      DB_PASSWORD: '${DB_PASSWORD}'

  db:
    image: 'mysql:8.0'
    container_name: my_super_docker-db
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'my_super_docker-mysql:/var/lib/mysql'
    networks:
      - my_super_docker-net

  adminer:
    container_name: my_super_docker-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - '${FORWARD_ADMINER_PORT:-8080}:8080'

networks:
  my_super_docker-net:
    driver: bridge

volumes:
  my_super_docker-mysql:
    driver: local
